venue:
  name: BINANCE
  account_type: MARGIN
  oms_type: NETTING
  starting_balances:
    - amount: 100000
      currency: USDT

strategy:
  module: strategy
  class: DonchianBreakoutStrategy
  config_class: DonchianBreakoutConfig
  config:
    order_id_tag: "001"
    trade_size: "20.0"
    entry_period: 20
    exit_period: 10

instrument:
  id: SOLUSDT.BINANCE
  kind: perpetual
  raw_symbol: SOLUSDT
  base_currency: SOL
  quote_currency: USDT
  settlement_currency: USDT
  price_precision: 3
  size_precision: 1
  price_increment: "0.001"
  size_increment: "0.1"
  lot_size: "0.1"
  maker_fee: "0.0002"
  taker_fee: "0.0005"
  bar_type: SOLUSDT.BINANCE-1-HOUR-LAST-EXTERNAL
